### ISSUE TITLE
Update ring api

### ISSUE THREAD

**Issue by theimo1221** [iobroker-community-adapters/ioBroker.ring#139]
As mentioned by dgreif (https://github.com/dgreif/ring/issues/697#issuecomment-897340429), updating to 9.20.1 might further reduce the problems around #137

**Comment by Mikee1234K** [comment]
Hi, not sure this is the right place to post this. I am using the iobroker.ring 1.2.3, since I have updated I noticed that instead of posting ding (for doorbell ringing) and motion, it will always send value ringing. The problem is obviously now that every motion triggers my iobroker routines for ringing the doorbell... I guess that ring have changed something in the api ?

**Comment by theimo1221** [comment]
To confirm that, we'd need to check wether ring or the api changed in that direction. As of now i can't answer this directly

**Comment by Mikee1234K** [comment]
I have found the issue. I was using state. That gives you ringing no matter if its motion or ringing. In Kind, its ding or motion.
