### ISSUE TITLE
Ring-Instanz lässt sich nicht mehr starten

### ISSUE THREAD

**Issue by evazoe1410** [iobroker-community-adapters/ioBroker.ring#405]
**Describe the bug**  

seit 2 Wochen kann ich die Ring-Instanz nicht mehr starten und erhalte im Log nachfolgenden Fehler. Das Update auf die aktuelle Adapter-Version hat den Fehler nicht behoben.

2022-11-22 13:47:47.623	error	locs is not iterable
2022-11-22 13:47:47.622	error	TypeError: locs is not iterable at opt/iobroker/node_modules/iobroker.ring/build/lib/ringApiClient.js:144:35 at processTicksAndRejections (node:internal/process/task_queues:96:5)
2022-11-22 13:47:47.622	error	unhandled promise rejection: locs is not iterable
2022-11-22 13:47:47.621	error	Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch().
2022-11-22 13:47:47.612	error	Api Call failed

**Comment by crusader85** [comment]
same here

**Comment by skyper19899** [comment]
Ja startet bei mir auch nicht hat schon einer eine Lösung gefunden für das Problem

**Comment by ddsak** [comment]
Hab auf die 2.0.0 Beta 3 zurück gerüstet. Damit gehts.

**Comment by theimo1221** [comment]
Hello,

Do you have any cameras in your location already?

Best Regards
Thiemo

**Comment by denjo1982** [comment]
bei mir auch
`<html>
<body>


host.iobroker | 2022-11-29 20:50:47.230 | error | instance system.adapter.ring.0 terminated with code 1 (JS_CONTROLLER_STOPPED)
-- | -- | -- | --
host.iobroker | 2022-11-29 20:50:47.230 | error | Caught by controller[0]: }
host.iobroker | 2022-11-29 20:50:47.229 | error | Caught by controller[0]: code: 'ERR_PACKAGE_PATH_NOT_EXPORTED'
host.iobroker | 2022-11-29 20:50:47.229 | error | Caught by controller[0]: at Object.<anonymous> (/opt/iobroker/node_modules/iobroker.ring/build/lib/ringApiClient.js:4:15) {
host.iobroker | 2022-11-29 20:50:47.229 | error | Caught by controller[0]: at require (node:internal/modules/cjs/helpers:103:18)
host.iobroker | 2022-11-29 20:50:47.229 | error | Caught by controller[0]: at Module.require (node:internal/modules/cjs/loader:1057:19)
host.iobroker | 2022-11-29 20:50:47.229 | error | Caught by controller[0]: at Function.Module._load (node:internal/modules/cjs/loader:833:27)
host.iobroker | 2022-11-29 20:50:47.229 | error | Caught by controller[0]: at Function.Module._resolveFilename (node:internal/modules/cjs/loader:971:27)
host.iobroker | 2022-11-29 20:50:47.229 | error | Caught by controller[0]: at Function.Module._findPath (node:internal/modules/cjs/loader:562:31)
host.iobroker | 2022-11-29 20:50:47.228 | error | Caught by controller[0]: at resolveExports (node:internal/modules/cjs/loader:522:36)
host.iobroker | 2022-11-29 20:50:47.228 | error | Caught by controller[0]: at packageExportsResolve (node:internal/modules/esm/resolve:649:3)
host.iobroker | 2022-11-29 20:50:47.228 | error | Caught by controller[0]: at throwExportsNotFound (node:internal/modules/esm/resolve:365:9)
host.iobroker | 2022-11-29 20:50:47.228 | error | Caught by controller[0]: at new NodeError (node:internal/errors:387:5)
host.iobroker | 2022-11-29 20:50:47.228 | error | Caught by controller[0]: Error [ERR_PACKAGE_PATH_NOT_EXPORTED]: Package subpath './lib/api/api' is not defined by "exports" in /opt/iobroker/node_modules/ring-client-api/package.json
host.iobroker | 2022-11-29 20:50:47.228 | error | Caught by controller[0]: ^
host.iobroker | 2022-11-29 20:50:47.227 | error | Caught by controller[0]: throw e;
host.iobroker | 2022-11-29 20:50:47.227 | error | Caught by controller[0]: node:internal/modules/cjs/loader:528


</body>
</html>`

**Comment by ckvsoft** [comment]
Hallo
Habe Heut den Adapter installiert. Funktionier auch bei mir nicht:



host.stallone | 2022-12-04 20:00:15.882 | info | Restart adapter system.adapter.ring.0 because enabled
-- | -- | -- | --
host.stallone | 2022-12-04 20:00:15.882 | error | instance system.adapter.ring.0 terminated with code 1 (JS_CONTROLLER_STOPPED)
host.stallone | 2022-12-04 20:00:15.882 | error | Caught by controller[0]: }
host.stallone | 2022-12-04 20:00:15.882 | error | Caught by controller[0]:   code: 'ERR_PACKAGE_PATH_NOT_EXPORTED'
host.stallone | 2022-12-04 20:00:15.882 | error | Caught  by controller[0]:     at Object.<anonymous>  (/opt/iobroker/node_modules/iobroker.ring/build/lib/ringApiClient.js:4:15)  {
host.stallone | 2022-12-04 20:00:15.882 | error | Caught by controller[0]:     at require (node:internal/modules/cjs/helpers:103:18)
host.stallone | 2022-12-04 20:00:15.882 | error | Caught by controller[0]:     at Module.require (node:internal/modules/cjs/loader:1057:19)
host.stallone | 2022-12-04 20:00:15.882 | error | Caught by controller[0]:     at Function.Module._load (node:internal/modules/cjs/loader:833:27)
host.stallone | 2022-12-04 20:00:15.882 | error | Caught by controller[0]:     at Function.Module._resolveFilename (node:internal/modules/cjs/loader:971:27)
host.stallone | 2022-12-04 20:00:15.882 | error | Caught by controller[0]:     at Function.Module._findPath (node:internal/modules/cjs/loader:562:31)
host.stallone | 2022-12-04 20:00:15.882 | error | Caught by controller[0]:     at resolveExports (node:internal/modules/cjs/loader:522:36)
host.stallone | 2022-12-04 20:00:15.882 | error | Caught by controller[0]:     at packageExportsResolve (node:internal/modules/esm/resolve:649:3)
host.stallone | 2022-12-04 20:00:15.882 | error | Caught by controller[0]:     at throwExportsNotFound (node:internal/modules/esm/resolve:365:9)
host.stallone | 2022-12-04 20:00:15.882 | error | Caught by controller[0]:     at new NodeError (node:internal/errors:387:5)
host.stallone | 2022-12-04 20:00:15.882 | error | Caught  by controller[0]: Error [ERR_PACKAGE_PATH_NOT_EXPORTED]: Package  subpath './lib/api/api' is not defined by "exports" in  /opt/iobroker/node_modules/ring-client-api/package.json
host.stallone | 2022-12-04 20:00:15.881 | error | Caught by controller[0]:       ^
host.stallone | 2022-12-04 20:00:15.881 | error | Caught by controller[0]:       throw e;
host.stallone | 2022-12-04 20:00:15.881 | error | Caught by controller[0]: node:internal/modules/cjs/loader:528
host.stallone | 2022-12-04 20:00:15.554 | info | instance system.adapter.ring.0 started with pid 39049
host.stallone | 2022-12-04 19:59:45.527 | info | Restart adapter system.adapter.ring.0 because enabled

**Comment by theimo1221** [comment]
Welche Version versucht ihr zu installieren?

**Comment by ckvsoft** [comment]
Verfügbare Version:
3.1.3

**Comment by theimo1221** [comment]
Versuch mal die 3.2.2

**Comment by ckvsoft** [comment]
> Versuch mal die 3.2.2

Ja danke. Diese Version wird mir nun auch im ioBroker angeboten. Kann isnstalliert werden und funktioniert auch mal soweit.

**Comment by evazoe1410** [comment]
Hallo, 
bei mir funktioniert auch die Version 3.2.2 nicht, gleiche Fehler wie vorher.
<html>
<body>


host.raspi-iobroker | 2022-12-11 19:16:51.551 | error | instance system.adapter.ring.0 terminated by request of the instance itself and will not be restarted, before user restarts it.
-- | -- | -- | --
ring.0 | 2022-12-11 19:16:50.864 | error | locs is not iterable
ring.0 | 2022-12-11 19:16:50.863 | error | TypeError: locs is not iterable at /opt/iobroker/node_modules/iobroker.ring/build/lib/ringApiClient.js:144:35 at processTicksAndRejections (node:internal/process/task_queues:96:5)
ring.0 | 2022-12-11 19:16:50.862 | error | unhandled promise rejection: locs is not iterable
ring.0 | 2022-12-11 19:16:50.861 | error | Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch().
ring.0 | 2022-12-11 19:16:50.854 | error | Api Call failed


</body>
</html>

**Comment by theimo1221** [comment]
Habend,

Hast du mindestens ein Gerät in deinem Ring Standort?

Vg Thiemo

**Comment by evazoe1410** [comment]
Hallo,
ja, einige. Hat ja auch bis vor wenigen Wochen einwandfrei funktioniert. Kann sein dass es nach Umstellung der Objektdatenverwaltung von JSON auf Redis und wieder zurück nicht mehr startbar ist, bin mir aber nicht sicher. Habe auch den Adapter schon gelöscht und neu installiert, ändert aber nichts.

**Comment by theimo1221** [comment]
Hast du ein frisches Token generiert?

**Comment by evazoe1410** [comment]
Hallo,
das hat in der Tat das Problem gelöst. Die Fehler haben aber überhaupt nicht auf ein ungültiges Token hingewiesen wobei ja auch seit einigen Versionen die Tokens nicht mehr ablaufen bzw. automatisch aktualisiert werden, oder ? Trotzdem vielen Dank für den Hinweis.

**Comment by theimo1221** [comment]
Ja die Meldung ist überarbeitungsbedürftig
