### ISSUE TITLE
2-factor authentication funktioniert nicht

### ISSUE THREAD

**Issue by Christian9377** [iobroker-community-adapters/ioBroker.ring#42]
Hallo, benutze die aktuelle Version, bekomme aber leider keine Anmeldung mit dem Adapter hin. Folgendes steht im Log vom Iobroker:

 Caught by controller[0]: This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). 

 Caught by controller[1]: Error: Your Ring account is configured to use 2-factor authentication (2fa). See https://github.com/dgreif/ring/wiki/Refresh-Tokens for details.

 Caught by controller[1]: at RingRestClient.<anonymous> (/opt/iobroker/node_modules/iobroker.ring/node_modules/ring-client-api/lib/api/rest-client.js:121:27)

Der Token wurde über die Konsole generiert und auch im Adapter gespeichert. Trotzdem die Meldung und immer wieder ein neuer Sicherheitscode über die Ring App. Was mache ich hier falsch? Kennt jemand dieses Problem?

**Comment by schmupu** [comment]
please, we need following infos below.

**Screenshots & Logfiles**  
If applicable, add screenshots and logfiles to help explain your problem. 

**Versions:**  
 - Shelly Adapter version: <adapter-version>
 - CoAP or MQTT protocol: <COAP|MQTT>
 - Shelly Firmware version: <version of firmware>
 - JS-Controller version: <js-controller-version> 
 - Node version: <node-version> 
 - Operating system: <os-name>

**Comment by Cadaux** [comment]
Versions:

Ring Adapter version: 1.1.3
JS-Controller version: 3.1.6
Node version: 10.19.0
Operating system: debian 10.3.0 (updated + upgradet)

I got the refreshToken via:
/opt/iobroker/node_modules/iobroker.ring/node_modules/ring-client-api$ node ring-auth-cli

Therefore I have not installed the homebridge ui which is mentioned here: https://github.com/dgreif/ring/wiki/Refresh-Tokens - Is this the problem?

and pasted everything between the "" into the instance (Refreshtoken (Two Face Auth)).
Verified the Email and Password and after I started the instance I got a sms with a new security code.

The log file:

`

ring.0 | 2020-09-01 18:36:09.544 | error | at process._tickCallback (internal/process/next_tick.js:68:7)
-- | -- | -- | --
ring.0 | 2020-09-01 18:36:09.544 | error | at rejected (/opt/iobroker/node_modules/iobroker.ring/node_modules/ring-client-api/lib/api/rest-client.js:25:65)
ring.0 | 2020-09-01 18:36:09.544 | error | at Generator.throw (<anonymous>)
ring.0 | 2020-09-01 18:36:09.544 | error | at RingRestClient.<anonymous> (/opt/iobroker/node_modules/iobroker.ring/node_modules/ring-client-api/lib/api/rest-client.js:134:27)
ring.0 | 2020-09-01 18:36:09.544 | error | (13108) Error: Your Ring account is configured to use 2-factor authentication (2fa). See https://github.com/dgreif/ring/wiki/Refresh-Tokens for details.
ring.0 | 2020-09-01 18:36:09.542 | error | (13108) unhandled promise rejection: Your Ring account is configured to use 2-factor authentication (2fa). See https://github.com/dgreif/ring/wiki/Refresh-Tokens for details.
Unhandled | 2020-09-01 18:36:09.542 | error | promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch().
ring.0 | 2020-09-01 18:36:09.542 | info | (13108) Terminated (ADAPTER_REQUESTED_TERMINATION): Without reason
ring.0 | 2020-09-01 18:36:09.541 | error | (13108) Could not start the Adapter ring.0 in version 1.1.3 because of Error: Your Ring account is configured to use 2-factor authentication (2fa). See https://github.com/dgreif/ring/wiki/Refresh-To
ring.0 | 2020-09-01 18:36:08.943 | info | (13108) Setting two face authentication and delete email and password from configuration afterwards
ring.0 | 2020-09-01 18:36:08.920 | info | (13108) Starting Adapter ring.0 in version 1.1.3
ring.0 | 2020-09-01 18:36:08.906 | info | (13108) starting. Version 1.1.3 in /opt/iobroker/node_modules/iobroker.ring, node: v10.19.0, js-controller: 3.1.6

`

**Comment by Christian9377** [comment]
Bei mir sind die selben log Daten.
Es gab heute sogar ein update aber das Problem ist das selbe.

**Comment by Christian9377** [comment]
Do you have new informations for this issue?

**Comment by schmupu** [comment]
da wird es kein adapter update geben. da kann ich leider nichts machen

**Comment by Andyexe** [comment]
Hallo,


    Ring Adapter version: ware> 1.1.3
    JS-Controller version: 3.1.6
    Node version: v12.19.0
    Operating system: Ubuntu


ist der Adapter nur für die Klingel gedacht oder kann ich auch die Ring Stick Up Cam Plug-In einbinden?
Ich bekomme bei der 2-factor authentication nur den Verifizierungscode: 054624

und die Fehlermeldung:

ring.0 | 2020-10-24 19:11:20.506 | error | (1626196) Error: Could not get devices in getAllRingsDevices(). Error:  Could not get all doorbell devices in getAllRingsDeviceObjects(). Error:  Could not get device instance in method getDevices(). E

Grüße
Andreas

**Comment by Pete28** [comment]
Habe auch gerade genau das selbe Problem.
Die Ring app ist ja auch alles andere als benutzerfreundlich und macht was sie will wenn man den code anfordert.
